title: 'Prácticas de Aprendizaje y Desarrollo de la Tecnología'
subtitle: 'Apuntes de Paula'
theme: jekyll-theme-midnight
light: true
description: 'Apuntes de la asignatura'
acronym: T1E
exclude: [ '_drafts/2021/', '_drafts/2020' ]
baseurl: '/asignatura-website-paula-alcantara-gutierrez-0100815207/' # '/introduccion'
#url: https://ull-mfp-aet-2324.github.io/asignatura-website-paula-alcantara-gutierrez-0100815207
guia_docente: https://www.ull.es/apps/guias/guias/view_guide_course/2223/125771143
show_downloads: false
calendario_academico: 
horarios_examenes: 
calendario_examenes: 
horarios_tutorias: 
organization: 
  url: https://github.com/ULL-MFP-AET-2324-alu0100815207
  name: ULL-MFP-AET-2324-alu0100815207
  master: https://github.dev/ULL-MFP-AET/ull-mfp-aet.github.io/blob/main/
apuntes_repo: https://github.com/ULL-MFP-AET/ull-mfp-aet.github.io/
campus_virtual: https://github.com/ULL-MFP-AET-2324/equipos-eq-cristian-oscar-paula
tareas_en_el_campus: https://github.com/ULL-MFP-AET-2324/equipos-eq-cristian-oscar-paula/issues
profesor: https://github.com/Paula150395
profesor_github: Paula150395
chat: https://chat.google.com
future: true
disqus: 
  url: https://procesadores-de-lenguajes.disqus.com/embed.js
  comments: true
classroom: 
  url: https://classroom.github.com/classrooms/149107114-ull-mfp-aet-2324-alu0100815207
  name: ULL-MFP-AET-2324-alu0100815207
collections:
  tareas:
    output: true
temas:
# - title: 'Introducción al Desarrollo Colaborativo de Proyectos en la Nube'
#    url: '/tema0-introduccion/'
#    hover: 'introduccion'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con GitHub Education'
#  url: '/tema1-github-education'
#  hover: 'github-education'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con Google'
#  url: /tema2-google-app-scripts
#  hover: 'google-app-scripts' 
plugins:
  - jemoji

